#!/usr/bin/env node

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const rootPath = dirname(dirname(fileURLToPath(import.meta.url)));
const outputPath = join(rootPath, "src/generated-materials.ts");

const categoryRoots = [
  ["entrypoint", "SKILL.md"],
  ["agent", "agents"],
  ["asset", "assets"],
  ["evaluation", "evals/blind-run-contract.md"],
  ["example", "examples"],
  ["reference", "references"],
  ["template", "templates"],
];

const allowedExtensions = new Set([".css", ".html", ".json", ".md", ".yaml", ".yml"]);

function collect(path) {
  const absolute = join(rootPath, path);
  if (statSync(absolute).isFile()) return [path];
  return readdirSync(absolute, { withFileTypes: true })
    .flatMap((entry) => collect(join(path, entry.name)))
    .sort();
}

function titleFor(path, content) {
  const heading = content.match(/^#\s+(.+)$/m)?.[1]?.trim();
  if (heading) return heading;
  return path.split("/").at(-1)?.replace(/[-_]/g, " ") ?? path;
}

function mimeFor(path) {
  const extension = extname(path);
  if (extension === ".css") return "text/css";
  if (extension === ".html") return "text/html";
  if (extension === ".json") return "application/json";
  if (extension === ".yaml" || extension === ".yml") return "application/yaml";
  return "text/markdown";
}

const materials = categoryRoots.flatMap(([category, path]) =>
  collect(path)
    .filter((candidate) => allowedExtensions.has(extname(candidate)))
    .map((candidate) => {
      const content = readFileSync(join(rootPath, candidate), "utf8");
      return {
        id: candidate,
        category,
        title: titleFor(candidate, content),
        mimeType: mimeFor(candidate),
        lineCount: content.split("\n").length,
        content,
      };
    }),
);

materials.sort((left, right) => left.id.localeCompare(right.id));

const skill = materials.find((material) => material.id === "SKILL.md");
if (!skill) throw new Error("SKILL.md was not included in the generated material set");
const packageVersion = JSON.parse(readFileSync(join(rootPath, "package.json"), "utf8")).version;

const source =
  "// Generated by scripts/generate_materials.mjs. Do not edit.\n" +
  `export const MATERIALS = ${JSON.stringify(materials, null, 2)} as const;\n` +
  `export const SKILL_CONTENT = ${JSON.stringify(skill.content)};\n` +
  `export const PACKAGE_VERSION = ${JSON.stringify(packageVersion)};\n`;

writeFileSync(outputPath, source, "utf8");
console.error(`Generated ${materials.length} MCP materials at ${relative(rootPath, outputPath)}`);
