#!/usr/bin/env node

import { createHash } from "node:crypto";
import { existsSync, lstatSync, readFileSync, readdirSync, realpathSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const rootPath = dirname(dirname(fileURLToPath(import.meta.url)));
const outputPath = join(rootPath, "src/generated-materials.ts");
const checkOnly = process.argv.includes("--check");

const categoryRoots = [
  ["entrypoint", "SKILL.md"],
  ["agent", "agents"],
  ["asset", "assets"],
  ["evaluation", "evals"],
  ["example", "examples"],
  ["reference", "references"],
  ["template", "templates"],
];

const allowedExtensions = new Set([".css", ".html", ".json", ".md", ".svg", ".xml", ".yaml", ".yml"]);
const localEvidenceAssets = new Set([
  "assets/codebase-state-dashboard/case-study-okgo.html",
  "assets/codebase-state-dashboard/model-scorecard-okgo.html",
  "assets/codebase-state-dashboard/okgo-case-study-state.json",
  "assets/codebase-state-dashboard/okgo-main-history.json",
  "assets/codebase-state-dashboard/okgo-model-scorecard.json",
]);
const localEvidencePrefixes = ["assets/codebase-state-dashboard/receipts/"];

function collect(path) {
  const absolute = join(rootPath, path);
  const metadata = lstatSync(absolute);
  if (metadata.isSymbolicLink()) throw new Error(`material source symlink is forbidden: ${path}`);
  if (metadata.isFile()) return [path];
  if (!metadata.isDirectory()) throw new Error(`material source is not a regular file or directory: ${path}`);
  const canonicalRoot = realpathSync(rootPath);
  const canonicalDirectory = realpathSync(absolute);
  if (canonicalDirectory !== canonicalRoot && !canonicalDirectory.startsWith(`${canonicalRoot}/`)) {
    throw new Error(`material source escapes repository root: ${path}`);
  }
  return readdirSync(absolute, { withFileTypes: true })
    .flatMap((entry) => collect(join(path, entry.name)))
    .sort(compareCodePoints);
}

function compareCodePoints(left, right) {
  const leftPoints = Array.from(left, (value) => value.codePointAt(0) ?? 0);
  const rightPoints = Array.from(right, (value) => value.codePointAt(0) ?? 0);
  for (let index = 0; index < Math.min(leftPoints.length, rightPoints.length); index += 1) {
    const difference = leftPoints[index] - rightPoints[index];
    if (difference) return difference;
  }
  return leftPoints.length - rightPoints.length;
}

function titleFor(path, content) {
  const heading = content.match(/^#\s+(.+)$/m)?.[1]?.trim();
  if (heading) return heading;
  return path.split("/").at(-1)?.replace(/[-_]/g, " ") ?? path;
}

function mimeFor(path) {
  const extension = extname(path);
  if (extension === ".css") return "text/css";
  if (extension === ".html") return "text/html";
  if (extension === ".json") return "application/json";
  if (extension === ".svg") return "image/svg+xml";
  if (extension === ".xml") return "application/xml";
  if (extension === ".yaml" || extension === ".yml") return "application/yaml";
  return "text/markdown";
}

const materials = categoryRoots.flatMap(([category, path]) =>
  collect(path)
    .filter((candidate) => allowedExtensions.has(extname(candidate))
      && !localEvidenceAssets.has(candidate)
      && !localEvidencePrefixes.some((prefix) => candidate.startsWith(prefix)))
    .map((candidate) => {
      const content = readFileSync(join(rootPath, candidate), "utf8");
      return {
        id: candidate,
        category,
        title: titleFor(candidate, content),
        mimeType: mimeFor(candidate),
        lineCount: content.split("\n").length,
        content,
      };
    }),
);

materials.sort((left, right) => compareCodePoints(left.id, right.id));

const skill = materials.find((material) => material.id === "SKILL.md");
if (!skill) throw new Error("SKILL.md was not included in the generated material set");
const packageVersion = JSON.parse(readFileSync(join(rootPath, "package.json"), "utf8")).version;
const materialsSha256 = createHash("sha256").update(JSON.stringify(materials)).digest("hex");

const source =
  "// Generated by scripts/generate_materials.mjs. Do not edit.\n" +
  `export const MATERIALS = ${JSON.stringify(materials, null, 2)} as const;\n` +
  `export const SKILL_CONTENT = ${JSON.stringify(skill.content)};\n` +
  `export const MATERIALS_SHA256 = ${JSON.stringify(materialsSha256)};\n` +
  `export const PACKAGE_VERSION = ${JSON.stringify(packageVersion)};\n`;

if (checkOnly) {
  if (!existsSync(outputPath) || readFileSync(outputPath, "utf8") !== source) {
    throw new Error(`generated MCP materials are stale: ${relative(rootPath, outputPath)}`);
  }
} else {
  writeFileSync(outputPath, source, "utf8");
}
console.error(`${checkOnly ? "Verified" : "Generated"} ${materials.length} MCP materials at ${relative(rootPath, outputPath)}`);
