import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { chmodSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, unlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative } from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import { verifyGeneratedCandidate } from "./verify_generated_candidate.js";

const roots: string[] = [];

function put(root: string, path: string, content: string, mode = 0o644): void {
  const target = join(root, path);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, content, { mode });
  chmodSync(target, mode);
}

function command(root: string, executable: string, args: readonly string[]): void {
  execFileSync(executable, args, { cwd: root, stdio: "pipe" });
}

function sourceGitMetadata(root: string): unknown {
  const gitPath = (name: string): string => execFileSync("git", ["--no-optional-locks", "-C", root, "rev-parse", "--path-format=absolute", "--git-path", name], {
    encoding: "utf8", env: { ...process.env, GIT_OPTIONAL_LOCKS: "0" },
  }).trim();
  const signature = (path: string): unknown => {
    const metadata = lstatSync(path, { bigint: true });
    return {
      path,
      mode: metadata.mode.toString(),
      size: metadata.size.toString(),
      mtime_ns: metadata.mtimeNs.toString(),
      sha256: metadata.isFile() ? createHash("sha256").update(readFileSync(path)).digest("hex") : null,
    };
  };
  const index = gitPath("index");
  const objects = gitPath("objects");
  const objectRows: unknown[] = [];
  const visit = (directory: string): void => {
    for (const entry of readdirSync(directory, { withFileTypes: true }).sort((left, right) => left.name.localeCompare(right.name))) {
      const path = join(directory, entry.name);
      if (entry.isDirectory()) visit(path);
      else objectRows.push({ relative: relative(objects, path), signature: signature(path) });
    }
  };
  visit(objects);
  return { index: signature(index), objects: objectRows };
}

function fixture(): string {
  const root = mkdtempSync(join(tmpdir(), "mc-generated-verifier-"));
  roots.push(root);
  put(root, ".gitignore", "node_modules/\n");
  put(root, "package.json", `${JSON.stringify({
    name: "generated-verifier-fixture",
    version: "1.0.0",
    scripts: { "build:raw": "bun scripts/build.ts" },
  }, null, 2)}\n`);
  put(root, "src/source.txt", "alpha\n");
  put(root, "scripts/build.ts", [
    'import { chmodSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";',
    'import { dirname, join } from "node:path";',
    'const root = process.cwd();',
    'const source = readFileSync(join(root, "src/source.txt"), "utf8");',
    'const outputs = new Map([',
    '  ["assets/codebase-state-dashboard/model-scorecard-interactions.js", `js:${source}`],',
    '  ["assets/codebase-state-dashboard/model-scorecard.html", `html:${source}`],',
    '  ["bin/mister-clean.js", `#!/usr/bin/env node\\ncli:${source}`],',
    '  ["MANIFEST.sha256", `manifest:${source}`],',
    ']);',
    'for (const [path, bytes] of outputs) {',
    '  const target = join(root, path); mkdirSync(dirname(target), { recursive: true });',
    '  writeFileSync(target, bytes, "utf8"); chmodSync(target, path.startsWith("bin/") ? 0o755 : 0o644);',
    '}',
    "",
  ].join("\n"));
  mkdirSync(join(root, "node_modules"));
  command(root, "bun", ["run", "build:raw"]);
  command(root, "git", ["init", "--quiet", "--initial-branch=main"]);
  command(root, "git", ["config", "user.name", "Generated Fixture"]);
  command(root, "git", ["config", "user.email", "generated-fixture.invalid"]);
  command(root, "git", ["add", "--all"]);
  command(root, "git", ["commit", "--quiet", "-m", "fresh generated fixture"]);
  return root;
}

afterEach(() => {
  while (roots.length) rmSync(roots.pop()!, { recursive: true, force: true });
});

describe("isolated generated candidate verification", () => {
  it("accepts fresh generated bytes without changing the source RepositoryObject", () => {
    const root = fixture();
    const before = readFileSync(join(root, "bin/mister-clean.js"), "utf8");
    expect(() => verifyGeneratedCandidate(root, "worktree")).not.toThrow();
    expect(readFileSync(join(root, "bin/mister-clean.js"), "utf8")).toBe(before);
  });

  it("computes a staged tree without mutating the source index or object database", () => {
    const root = fixture();
    const before = sourceGitMetadata(root);
    expect(() => verifyGeneratedCandidate(root, "staged")).not.toThrow();
    expect(sourceGitMetadata(root)).toEqual(before);
  });

  it("preserves a tracked deletion in the exact worktree candidate", () => {
    const root = fixture();
    put(root, "retired.lock", "obsolete\n");
    command(root, "git", ["add", "retired.lock"]);
    command(root, "git", ["commit", "--quiet", "-m", "track obsolete lock"]);
    unlinkSync(join(root, "retired.lock"));
    command(root, "bun", ["run", "build:raw"]);

    expect(() => verifyGeneratedCandidate(root, "worktree")).not.toThrow();
  });

  it("rejects coherently stale generated bytes after source changes", () => {
    const root = fixture();
    put(root, "src/source.txt", "beta\n");
    expect(() => verifyGeneratedCandidate(root, "worktree")).toThrow(/fresh isolated build differs/u);
    expect(readFileSync(join(root, "bin/mister-clean.js"), "utf8")).toContain("alpha");
  });

  it("adjudicates the staged candidate independently of matching unstaged repairs", () => {
    const root = fixture();
    put(root, "src/source.txt", "beta\n");
    command(root, "git", ["add", "src/source.txt"]);
    command(root, "bun", ["run", "build:raw"]);
    expect(readFileSync(join(root, "bin/mister-clean.js"), "utf8")).toContain("beta");
    expect(() => verifyGeneratedCandidate(root, "staged")).toThrow(/fresh isolated build differs/u);
  });
});
