import type { RemediationWaveManifest } from "../contracts/wave-directive.js";
import type { IsoTimestamp, Sha256 } from "../contracts/primitives.js";

export const TEST_NOW = "2026-08-26T12:00:00.000Z" as IsoTimestamp;
export const testSha = (value: string): Sha256 => value.repeat(64) as Sha256;

export function validManifestValue(revision = 1, parentManifestSha256: Sha256 | null = null): RemediationWaveManifest {
  return {
    record_type: "mister-clean.action-manifest",
    schema_version: "1.3",
    manifest_kind: "remediation_wave",
    manifest_id: "manifest-1",
    revision,
    parent_manifest_sha256: parentManifestSha256,
    run_id: "run-1",
    created_at: TEST_NOW,
    created_by: "controller",
    authority_mode: "OPERATE",
    repository: {
      repository_id: "repository-1",
      branch: "work",
      commit: "abc",
      tree: "def",
      repository_object_sha256: testSha("a"),
      observed_at: TEST_NOW,
    },
    target_ref: "refs/heads/work",
    expected_target_commit: "abc",
    detector_set_sha256: testSha("b"),
    policy_sha256: testSha("c"),
    issue_graph: { issue_graph_id: "graph-1", version: 1, sha256: testSha("d") },
    selected_issue_ids: ["issue-1"],
    optimization: {
      policy_id: "policy-1",
      severity_weight: 1,
      difficulty_weight: 1,
      unlock_value_weight: 0,
      regression_risk_weight: 1,
      cost_tiebreak: false,
      speed_tiebreak: false,
      overrides: [],
    },
    waves: [{
      wave_id: "wave-1",
      sequence: 1,
      state: "planned",
      prerequisite_wave_ids: [],
      tracks: [{ track_id: "track-1", lane_ids: ["lane-1"], issue_ids: ["issue-1"] }],
      integration_barrier: ["independent verification"],
    }],
    lanes: [{
      lane_id: "lane-1",
      task_id: "task-1",
      role: "writer",
      state: "queued",
      owner: "writer-agent",
      issue_ids: ["issue-1"],
      dependencies: [],
      worktree: "/repo-wt",
      branch: "work",
      baseline_commit: "abc",
      read_paths: ["src"],
      read_custody: {
        protected_paths: ["project/planning/holdout/**"],
        permitted_metadata_paths: ["project/planning/holdout-seals.json"],
        enforcement: "externalized",
        evidence: [{ path: "read-custody.json", sha256: testSha("7"), record_type: "mister-clean.read-custody" }],
      },
      write_paths: ["src/runtime.ts"],
      invariants: ["no false verification"],
      acceptance: ["holdout pass"],
      context_budget_tokens: 4096,
      assignment: {
        agent_tuple_id: "agent-tuple-1",
        execution_route_id: "route-1",
        required_capabilities: ["independent_qa_holdout"],
        routing_evidence: [{ path: "routing.json", sha256: testSha("e"), record_type: "routing" }],
        fallback_agent_tuple_id: null,
        fallback_execution_route_id: null,
      },
      lease: {
        lease_id: "lease-1",
        fencing_token: 7,
        worktree: "/repo-wt",
        branch: "work",
        owner: "writer-agent",
        expires_at: "2027-08-26T13:00:00.000Z",
      },
      coordination_claims: [{
        key: "domain-1",
        access: "write",
        expected_version: 3,
        expected_state_digest: testSha("8"),
        operation_class: "runtime-remediation",
        commutes_with: [],
        commutativity_ref: null,
      }],
    }],
    parent_operation_ids: [],
    no_harm_comparators: ["tracked-plus-nonignored"],
    native_gates: ["bun test"],
    rollback: ["abort without integration"],
    receipt_requirements: [{ role: "holdout", independent: true, required_claims: ["verified"] }],
    projections: [{ kind: "holdout_packet", schema_version: "1.0", sha256: testSha("f") }],
    terminal_issue_dispositions: [{ issue_id: "issue-1", required_terminal_state: "paid" }],
    hard_boundaries: ["no push"],
    excluded_actions: ["publish"],
    self_audit: {
      status: "passed",
      checked_at: TEST_NOW,
      evidence: [{ path: "self-audit.json", sha256: testSha("1"), record_type: "self-audit" }],
    },
  } as unknown as RemediationWaveManifest;
}
